version: 2.1

orbs:
  sonarscanner: psl/sonarscanner@0.0.4

jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t demo_nodejs_circleci -t kawtar2004/demo_nodejs_circleci:latest .
            echo $DOCKER_PASSWORD | docker login -u kawtar2004 --password-stdin
            docker push kawtar2004/demo_nodejs_circleci:latest

  scan:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace

  notify:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run:
          name: Notify on failure
          command: |
            # Envoyer une notification en cas d'échec du pipeline (exemple: Slack)
            if [ "$CIRCLE_JOB" != "scan" ]; then
              echo "Build failed"
              # Ajouter ici la logique pour envoyer une notification
            fi

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
      - build_docker_image
      - scan
      - notify:
          requires:
            - build_test
            - build_docker_image
            - scan
          filters:
            branches:
              ignore: /.*/
